# Generated by Django 2.2.5 on 2019-10-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'admin'), (1, 'tourist'), (2, 'touruser')], default=1, help_text='0:admin; 1:tourist,2:touruser'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
